### ISSUE TITLE
Line breaks are bugged in (at least) Firefox

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#109]
![q8dwjtq](https://cloud.githubusercontent.com/assets/6607512/22883377/e88035d6-f1e7-11e6-92a7-c85f50e601fc.png)

The above is in Firefox 51.0.1 on Windows 10. "NOT" and "coffee" are over two lines each.

If you see this happen, please let us know which URL you found it on, which browser and OS you were using, and if possible post a screenshot! Thank you. :)

**Comment by MyAlternateAccount** [comment]
Confirmed on Firefox 51.0.1 on Linux, on the feed main page:

![1487565874](https://cloud.githubusercontent.com/assets/25602160/23112317/13e34364-f6f5-11e6-87ac-77bea4466127.png)

Works on Chromium 56 on Linux:

![1487565946](https://cloud.githubusercontent.com/assets/25602160/23112338/324dbb86-f6f5-11e6-963f-60cfe34ce4fc.png)

The problem is in `style.css` on line 1035:

```css
.feed_inner_content {
    margin: 10px 10px 10px 20px;
    padding: 10px;
    max-width: 710px;
    display: inline-block;
    background-color: #E8E8E8;
    -ms-word-break: break-all;
    word-break: break-all;

 /* Non standard for webkit */
     word-break: break-word;
}
```

`word-break: break-all` allows the browser to break lines between any two characters, and Webkit (which Chromium/Chrome is based on) doesn't seem to support it. I'm not sure if this behavior is intentional, but I can confirm that removing that CSS rule does fix the issue in Firefox.
